import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";

import {
  NextIntlClientProvider,
  useMessages,
} from "next-intl";
import { useLocale } from "next-intl";

import Navbar from '../[locale]/components/Navbar';
import Footer from '../[locale]/components/Footer';
import Social from '../[locale]/components/Social';
import Canonical from '../[locale]/components/Canonical';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Plana",
  description: "Generated by Plana",
  keywords: ["home", "page", "homepage"],
  robots: 'index, follow', //Robots tag
  icons: {
    icon: '/images/favicon.ico',
  },
};

interface RootLayoutProps {
  children: ReactNode;
  params: { locale: string };
}

export default  function RootLayout({ children }: RootLayoutProps) {
  const locale = useLocale();

  const messages = useMessages();
  // const t = useTranslations();


  return (
    <html lang={locale} className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <body>
        <Canonical />
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          <Social />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
