import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { Geist, Geist_Mono } from "next/font/google";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import Navbar from '../[locale]/components/Navbar';
import Footer from '../[locale]/components/Footer';
import Social from '../[locale]/components/Social';
import Canonical from '../[locale]/components/Canonical';
import enMessages from '../../messages/en.json';
import idMessages from '../../messages/id.json';


const MESSAGES = {
  en: enMessages,
  id: idMessages,
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ["home", "page", "homepage"],
  robots: 'index, follow', //Robots tag
};

interface LayoutProps {
  params: { locale: string };
  children: React.ReactNode;
}

export default async function LocaleLayout(props: LayoutProps) {
  const { children, params } = props;
  const { locale } = params;

  // Load messages manually if needed
  if (!['en', 'id'].includes(locale)) notFound();

  const messages = MESSAGES[locale as keyof typeof MESSAGES];


  return (
    <html lang={locale} className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <body>
        <Canonical />
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          <Social />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
